canonical: http://fhir.ch/ig/ch-lab-order
id: ch.fhir.ig.ch-lab-order
name: CH_LAB_ORDER
title: CH LAB-Order (R4)
description: Implementation guide CH CH LAB-Order (R4)
status: active
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2025-12-15
version: 3.0.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: trial-use # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: HL7 Switzerland
  url: https://www.hl7.ch
contact:
  - name: Marcel Hanselmann
    telecom:
      - system: email
        value: laborprojektgruppe@gmail.com
        use: work

dependencies:
  ch.fhir.ig.ch-core: current
  ch.fhir.ig.ch-term: 
    uri: http://fhir.ch/ig/ch-term/ImplementationGuide/ch.fhir.ig.ch-term
    version: current # 3.3.x
  # hl7.terminology.r4:
  #   uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
  #   version: 6.3.0
  ch.fhir.ig.ch-orf: current # 3.0.1
   
pages:
  index.md:
    title: Home
  usecases-english.md:
    title: Use Cases
  usecases-german.md:
    title: Anwendungsfälle
  usecases-french.md:
    title: Cas d’application
  case-studies-english.md:
    title: Case Studies
  case-studies-german.md:
    title: Fallstudien
  case-studies-french.md:
    title: Études de cas
  document-lo-sr.md:
    title: CH LAB-Order with Service Request  
  document-lo-sr-and-form.md:
    title: CH LAB-Order with Service Request and Form
  profiles.md:
    title: Profiles
  terminology.md:
    title: Terminology
  changelog.md:
    title: Changelog

menu:
  Home: index.html
  Use Cases:
    English: usecases-english.html
    German: usecases-german.html
    French: usecases-french.html
  Case Studies:
    English: case-studies-english.html
    German: case-studies-german.html
    French: case-studies-french.html
  Document:
    Document with Service Request: document-lo-sr.html
    Document with Service Request and Form: document-lo-sr-and-form.html
  Profiles: profiles.html
  Terminology: terminology.html
  Artifacts: artifacts.html  
  Changelog: changelog.html

parameters:
  allow-extensible-warnings: true
  display-warnings: true  
  path-expansion-params: '../../expansion-params.json'  # for using SNOMED CT Swiss Extension
  pin-canonicals: pin-multiples

FSHOnly: false
applyExtensionMetadataToRoot: false
